### ISSUE TITLE
strange output

### ISSUE THREAD

**Issue by nyudenkov** [xekon/AardwolfMudlet#4]
```
l
Thrivaldi's Cave
{coords}0,30,20
{rdesc}
  This cave is completely dark and cold. Torches burn but don't emit light 
further than one foot away. The sound of heavy breathing echoes across the 
walls as well as the sound of something dragging across the ground. The only 
exit is to the west...if you can find it again.
{/rdesc}
```

Is this OK?

**Comment by Jieiku** [comment]
This was covered in the notes section of the readme, the aardmush client uses a bunch of tags, which can be turned off like this:

`tags bigmap off;tags coords off;tags mapexits off;tags mapnames off;tags roomdescs off`

very sorry for not responding sooner, somehow I missed this issue and have not had time to develop AardwolfMudlet package.
