### ISSUE TITLE
Mudlet for Linux no Main window.

### ISSUE THREAD

**Issue by schistkicker** [xekon/AardwolfMudlet#7]
Hello, I have this working on Windows but following same instructions/procedure in Linux Mint 20 using Mudlet 4.10.1 causes the main feed window section to be missing/not display (screenshot attached). Deleting profile folder in ~/.config/mudlet/ eliminates the issue but reinstall of this module recreates the problem. It also replicates across other profiles. Any thoughts on how to fix it?
![Screenshot from 2021-02-18 17-04-52](https://user-images.githubusercontent.com/34242180/108428456-99c60e80-720c-11eb-9ed7-830a5ed50b97.png)

**Comment by Leigheas** [comment]
It looks like there is a window covering the main outputs. Notice the blue 4 way arrows.
You could try to reset the profile which would undo any windows and  GUI stuff.

resetProfile
resetProfile()
Reloads your entire Mudlet profile - as if you've just opened it. All UI elements will be cleared, so this useful when you're coding your UI.
Example
resetProfile()
The function used to require input from the game to work, but as of Mudlet 3.20 that is no longer the case.

Note
Note: Don't put resetProfile() in the a script-item in the script editor as the script will be reloaded by resetProfile() as well better use

lua resetProfile()
in your commandline or make an Alias containing resetProfile().

**Comment by schistkicker** [comment]
Thank you for the option. I entered the code to reset the profile and
restarted but screen looks the same, all it seemed to do was reset the map
number from 10 down to 5. I moved the blue arrows you mentioned (I think
the correct ones) and it looks like the main window section is just super
narrow column width, could that be the issue?

**Comment by schistkicker** [comment]
Image showing blue 4-way arrows on left didn't show here it looks like, this is what I was talking about. It seems resize the status bars at the bottom too.
![Screenshot from 2021-02-18 17-48-59](https://user-images.githubusercontent.com/34242180/108435616-ce8b9300-7217-11eb-93e8-84bfeae18a8a.png)

**Comment by Jieiku** [comment]
WOA! very strange indeed. I am also a Linux user, how did you install Mudlet 4.10.1? did you download the appimage from the mudlet site or build it your self?

If I can reproduce this I can see if there is anything obvious that is the issue, if I cannot figure it out then the wonderful developers on the Mudlet Discord can probably help.

**Comment by schistkicker** [comment]
I built it myself. Please let me know if you can recreate it and what you
find out, otherwise I'll work through the Discord.

**Comment by Jieiku** [comment]
I was unable to reproduce the issue on Ubuntu 20.04 with Plasma/wayland.

Here is my complete install routine, I just built and installed mudlet today.
I am not sure if it will help, because I am using Ubuntu...

```
# install dependencies:
sudo apt install build-essential cmake git liblua5.1-dev zlib1g-dev libhunspell-dev libpcre3-dev \
libzip-dev libboost-dev libyajl-dev libpulse-dev lua-rex-pcre lua-filesystem lua-zip \
lua-sql-sqlite3 qt5-default qtmultimedia5-dev qttools5-dev luarocks ccache libpugixml-dev \
libqt5texttospeech5-dev qtspeech5-flite-plugin qtspeech5-speechd-plugin libqt5opengl5-dev \
lua5.1 libhunspell-dev libglu1-mesa-dev mesa-common-dev libglib2.0-dev libboost-all-dev \
libgstreamer1.0-dev qt5keychain-dev libsecret-1-dev

# install more dependencies:
sudo luarocks install lcf
sudo luarocks install luautf8
sudo luarocks install lua-yajl

# Download mudlet source
mkdir -p ~/source && cd ~/source
git clone --recursive https://github.com/Mudlet/Mudlet.git
mkdir ~/source/Mudlet/build && cd ~/source/Mudlet/build

# build mudlet
qmake ../src/mudlet.pro
make -j `nproc`
sudo make install
sudo cp ../mudlet.png /usr/share/pixmaps
sudo cp ../mudlet.desktop /usr/share/applications
```

```
# Download AardwolfMudlet:
mkdir -p ~/.config/mudlet/profiles && cd ~/.config/mudlet/profiles
git clone https://github.com/xekon/AardwolfMudlet Aardwolf
```

Install and configure AardwolfMudlet as shown in the Installation section at the top: https://github.com/xekon/AardwolfMudlet

Sorry I could not reproduce and be more help, I am hoping that maybe your just missing an optional dependency that causes this weirdness.

**Comment by schistkicker** [comment]
This method worked or seems to be working now, thank you for the
detailed explanation. I did a full purge and removal of any remnants of the
previous build and install. I'm not sure what the difference was from this
how-to versus the previous build attempts but something obviously was not
the same. I'm hopeful a restart or update to other software doesn't break
it...

Again thank you for taking the time to help with this!

**Comment by Jieiku** [comment]
no problem, happy it worked!
