### ISSUE TITLE
Cant disable noexp

### ISSUE THREAD

**Issue by kazagistar** [xekon/AardwolfMudlet#9]
There is a "feature" that turns off experience during campaigns. However, nowhere is it listed how to turn it off. and when I tried to change the variables or the config script and even restart it just kept turning noexp on over and over. Makes it unplayable.

**Comment by ZedTheYeti** [comment]
You can use the `vconfig` command to configure the settings for this plugin package. One of the config options is "CP Level noexp limit" which controls this auto-noexp feature. I've turned it off for myself by setting that value to -1, which you can do with command `vconfig cpexp -1`

![image](https://user-images.githubusercontent.com/9111935/117446844-51acb300-af02-11eb-8c31-196a9a5bdffc.png)

**Comment by Jieiku** [comment]
I added a note about this to the readme of the github project as well, thanks @ZedTheYeti
